version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - admin
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./.env:/.env:ro

  admin:
    build:
      context: ./admin
    volumes:
      - ./.env:/.env
      - ./admin/app:/app
      - static_root:/static_root/
      - services_config:/config
    depends_on:
      - db
      - harbor
      - icecast
      - redis
      - upstream

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  harbor:
    build:
      context: ./services
      dockerfile: Dockerfile.harbor
    volumes:
      - services_config:/config

  icecast:
    build:
      context: ./services
      dockerfile: Dockerfile.icecast
    ports:
      - '8000:8000'
    volumes:
      - services_config:/config

  upstream:
    build:
      context: ./services
      dockerfile: Dockerfile.upstream
    volumes:
      - services_config:/config

volumes:
  letsencrypt:
  postgres_data:
  redis_data:
  services_config:
  static_root:
