version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - admin
    volumes:
      - letsencrypt:/etc/letsencrypt
      - static_root:/usr/share/nginx/html/static_root:ro
      - ./.env:/.env:ro

  admin:
    build:
      context: ./admin
    volumes:
      - ./.env:/.env
      - ./admin/app:/app
      - static_root:/static_root
      - services_config:/config
    depends_on:
      - db
      - harbor
      - redis
      - upstream

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  harbor:
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile
    volumes:
      - services_config:/config:ro
    environment:
      CONTAINER_NAME: harbor

  upstream:
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile
    volumes:
      - services_config:/config:ro
    environment:
      CONTAINER_NAME: upstream

volumes:
  letsencrypt:
  postgres_data:
  redis_data:
  services_config:
  static_root:
