version: '3'

services:
  nginx:
    image: library/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      NGINX_LISTEN: |
        listen 80 default_server;
        listen [::]:80 default_server;
      DOMAIN_NAME:
