dev_addr: 127.0.0.1:8888  # Not used by docker-compose
edit_uri: ""
markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - toc:
        permalink: True
nav:
    - Home: index.md
    - User's Guide:
        - AutoDJ: users-guide/autodj.md
        - Prerecorded Broadcasts: users-guide/prerecorded-broadcasts.md
        - Live DJing:
            - Icecast 2: users-guide/dj/icecast.md
            - Zoom: users-guide/dj/zoom.md
            - RTMP: users-guide/dj/rtmp.md
    - Admin's Guide:
        - AutoDJ: admin-guide/autodj.md
        - Configuration: admin-guide/configuration.md
    - Server Setup: server-setup.md
    - Glossary of Terms: glossary.md
    - About:
        - License: about/license.md
        - Changelog: about/changelog.md
        - Author & Miscellany: about/author-miscellany.md
plugins:
    - macros:
        module_name: docs_macros
    - mermaid2:
        arguments:
            theme: dark
    - search
repo_name: dtcooper/carb
repo_url: https://github.com/dtcooper/carb
site_dir: _docs
site_name: Crazy Arms Radio Backend Documentation
site_url: https://crazyarms.xyz
theme:
    favicon: img/favicon.svg
    name: material
    features:
        - navigation.instant
        - navigation.sections
        - navigation.tabs
        - toc.integrate
    palette:
        scheme: slate
        primary: pink
        accent: light blue
    font:
        text: Inter
    icon:
        repo: fontawesome/brands/github
copyright: Copyright &copy; 2020-2021 David Cooper
