dev_addr: 127.0.0.1:8888  # Not used by docker-compose
edit_uri: ""
# Include mermaid
extra_javascript:
    - https://unpkg.com/mermaid@8.8.4/dist/mermaid.js
markdown_extensions:
    - admonition
    - def_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.tabbed
    - toc:
        permalink: True
nav:
    - Home: index.md
    - User's Guide:
        - Live DJing:
            - Icecast 2: users-guide/dj/icecast.md
            - Zoom: users-guide/dj/zoom.md
    - Admin's Guide:
        - AutoDJ: admin-guide/autodj.md
        - Configuration: admin-guide/configuration.md
    - Server Setup: server-setup.md
    - Glossary of Terms: glossary.md
repo_name: dtcooper/carb
repo_url: https://github.com/dtcooper/carb
site_dir: _docs
site_name: Crazy Arms Radio Backend Documentation
site_url: https://crazyarms.xyz
theme:
    favicon: img/favicon.svg
    name: material
    features:
        - navigation.instant
        - navigation.sections
        - navigation.tabs
        - toc.integrate
    palette:
        primary: black
        accent: amber
    font:
        text: Inter
        code: Inconsolata
    icon:
        repo: fontawesome/brands/github
copyright: Copyright &copy; 2020-2021 David Cooper
