version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - '${HTTP_PORT:-80}:80'
    depends_on:
      - app
      - logs
    volumes:
      - ./.env:/.env:ro
      - ./media:/media_root:ro
      - static_root:/static_root:ro
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

  app:
    container_name: app
    restart: always
    build:
      context: ./app
    volumes:
      - ./.env:/.env:ro
      - ./imports:/imports_root
      - ./media:/media_root
      - services_config:/config
      - static_root:/static_root
    depends_on:
      - db
      - harbor
      - redis
      - upstream
    environment:
      CRAZYARMS_VERSION: ${CRAZYARMS_VERSION:-unknown}
      TZ: ${TIMEZONE:-US/Pacific}

  tasks:
    container_name: tasks
    restart: always
    build:
      context: ./app
    volumes:
      - ./.env:/.env:ro
      - ./imports:/imports_root
      - ./media:/media_root
      - sftp_root:/sftp_root
    depends_on:
      - db
      - redis
    environment:
      CRAZYARMS_VERSION: ${CRAZYARMS_VERSION:-unknown}
      RUN_HUEY: 1
      TZ: ${TIMEZONE:-US/Pacific}

  log-subscriber:
    container_name: log-subscriber
    restart: always
    build:
      context: ./app
    volumes:
      - ./.env:/.env:ro
    depends_on:
      - db
      - redis
    command: ./manage.py run_log_subscriber
    environment:
      CRAZYARMS_VERSION: ${CRAZYARMS_VERSION:-unknown}
      TZ: ${TIMEZONE:-US/Pacific}

  db:
    container_name: db
    image: library/postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: ${TIMEZONE:-US/Pacific}

  redis:
    container_name: redis
    image: library/redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

  harbor:
    container_name: harbor
    restart: always
    build:
      context: ./liquidsoap
    ports:
      - '${HARBOR_PORT:-8001}:8001'
    depends_on:
      - db
    volumes:
      - services_config:/config:ro
      - ./media:/media_root:ro
    environment:
      CRAZYARMS_VERSION: ${CRAZYARMS_VERSION:-unknown}
      CONTAINER_NAME: harbor
      SECRET_KEY: ${SECRET_KEY}
      TZ: ${TIMEZONE:-US/Pacific}

  upstream:
    container_name: upstream
    restart: always
    build:
      context: ./liquidsoap
    depends_on:
      - db
    volumes:
      - ./media:/media_root:ro
      - services_config:/config:ro
    environment:
      CRAZYARMS_VERSION: ${CRAZYARMS_VERSION:-unknown}
      CONTAINER_NAME: upstream
      TZ: ${TIMEZONE:-US/Pacific}

  logs:
    container_name: logs
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_BASE: "/logs"
      DOZZLE_TAILSIZE: 5000
      TZ: ${TIMEZONE:-US/Pacific}

  sftp:
    container_name: sftp
    restart: always
    build:
      context: ./sftp
    volumes:
      - ./.env:/.env:ro
      - services_config:/config
      - sftp_root:/sftp_root
    ports:
      - "${SFTP_PORT:-2022}:2022"

volumes:
  postgres_data:
  redis_data:
  services_config:
  sftp_root:
  static_root:
