version: '3'

services:
  nginx:
    container_name: nginx
    image: dtcooper/carb-nginx:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app
      - logs
      - sse
    volumes:
      - static_root:/static_root:ro
      - ./media:/media_root:ro
      - ./.env:/.env:ro
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

  app:
    container_name: app
    image: dtcooper/carb-app:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./app
    volumes:
      - ./.env:/.env:ro
      - static_root:/static_root
      - ./media:/media_root
      - services_config:/config
    depends_on:
      - db
      - harbor
      - redis
      - upstream
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

  tasks:
    container_name: tasks
    image: dtcooper/carb-app:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./app
    volumes:
      - ./.env:/.env:ro
      - ./media:/media_root
    depends_on:
      - db
      - redis
    environment:
      RUN_HUEY: 1
      TZ: ${TIMEZONE:-US/Pacific}

  sse:
    container_name: sse
    image: dtcooper/carb-sse:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./sse
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

  db:
    container_name: db
    image: library/postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: ${TIMEZONE:-US/Pacific}

  redis:
    container_name: redis
    image: library/redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

  harbor:
    container_name: harbor
    image: dtcooper/carb-liquidsoap:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    depends_on:
      - db
    volumes:
      - services_config:/config:ro
      - ./media:/media_root:ro
    environment:
      CONTAINER_NAME: harbor
      TZ: ${TIMEZONE:-US/Pacific}

  upstream:
    container_name: upstream
    image: dtcooper/carb-liquidsoap:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - services_config:/config:ro
      - ./media:/media_root:ro
    environment:
      CONTAINER_NAME: upstream
      TZ: ${TIMEZONE:-US/Pacific}

  logs:
    container_name: logs
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_BASE: "/logs"
      DOZZLE_TAILSIZE: 5000
      TZ: ${TIMEZONE:-US/Pacific}

volumes:
  postgres_data:
  redis_data:
  services_config:
  static_root:
