services:
  nginx:
    depends_on:
      - harbor-telnet-web
  harbor-telnet-web:
    container_name: harbor-telnet-web
    image: dtcooper/carb-harbor-telnet:${CRAZYARMS_VERSION:-latest}
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile.harbor-telnet
    restart: always
    environment:
      TZ: ${TIMEZONE:-US/Pacific}
