services:
  nginx:
    depends_on:
      - harbor-telnet-web
  harbor-telnet-web:
    container_name: harbor-telnet-web
    image: dtcooper/crazyarms-harbor-telnet-web:${CRAZYARMS_VERSION}
    build:
      context: ./liquidsoap
      dockerfile: Dockerfile.harbor-telnet
    restart: always
    environment:
      TZ: ${TIMEZONE:-US/Pacific}
