services:
  nginx:
    depends_on:
      - harbor-telnet
  harbor-telnet:
    container_name: harbor-telnet
    image: tsl0922/ttyd:alpine
    restart: always
    command: ['ttyd', 'sh', '-c', 'echo "# Welcome to the Harbor telnet. Enter "help" + [ENTER] for more info." && exec nc harbor 1234']
