services:
  nginx:
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - '${HTTPS_PORT:-443}:443'

volumes:
  # TODO move this to services_config, and symlink /etc/letsencrypt
  letsencrypt:
