services:
  app:
    depends_on:
      - icecast

  icecast:
    container_name: icecast
    restart: always
    build:
      context: ./icecast
      dockerfile: Dockerfile
    ports:
      - '${ICECAST_PORT:-8000}:8000'
    volumes:
      - services_config:/config:ro
    environment:
      TZ: ${TIMEZONE:-US/Pacific}
