services:
  app:
    depends_on:
      - icecast

  icecast:
    container_name: icecast
    image: dtcooper/carb-icecast-kh:${CARB_VERSION:-latest}
    restart: always
    build:
      context: ./icecast
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - services_config:/config:ro
    environment:
      TZ: ${TIMEZONE:-US/Pacific}
