services:
  admin:
    depends_on:
      - icecast

  icecast:
    build:
      context: ./icecast
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - services_config:/config:ro
