services:
  rtmp:
    container_name: crazyarms-rtmp
    image: dtcooper/crazyarms-rtmp:${CRAZYARMS_VERSION}
    restart: always
    depends_on:
      - app
    volumes:
      - ./.env:/.env:ro
    build:
      context: ./rtmp
    ports:
      - "${RTMP_PORT:-1935}:1935"
