services:
  test:
    container_name: app
    image: dtcooper/carb-app:${CARB_VERSION:-latest}
    build:
      context: ./app
    volumes:
      - ./app/app:/app
    environment:
      DJANGO_SETTINGS_MODULE: carb.settings_test
      TZ: ${TIMEZONE:-US/Pacific}
      EMAIL_ENABLED: 1
      HARBOR_TELNET_WEB_ENABLED: 1
      ICECAST_ENABLED: 1
      RTMP_ENABLED: 1
      SFTP_ENABLED: 1
      ZOOM_ENABLED: 1
      SECRET_KEY: topsecret
    command: pytest
