services:
  app:
    depends_on:
      - zoom

  nginx:
    depends_on:
      - zoom

  zoom:
    container_name: zoom
    build:
      context: ./zoom
    volumes:
      - ./.env:/.env
      - services_config:/config
      - zoom_user_home:/home/user
    cap_add:
      - SYS_ADMIN

volumes:
  zoom_user_home:
