services:
  app:
    depends_on:
      - zoom

  nginx:
    depends_on:
      - zoom

  zoom:
    container_name: zoom
    image: dtcooper/crazyarms-zoom:${CRAZYARMS_VERSION:-latest}
    restart: always
    # Seems like Zoom works properly under QEMU for testing/development with `liunux/amd64`
    # emulation on on Apple M1 (linux/arm64/v8). Chrome doesn't, but that's fine.
    platform: linux/amd64
    build:
      context: ./zoom
    volumes:
      - services_config:/config
      - zoom_user_home:/home/user
    cap_add:
      - SYS_ADMIN
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

volumes:
  zoom_user_home:
