services:
  app:
    depends_on:
      - zoom

  nginx:
    depends_on:
      - zoom

  zoom:
    container_name: zoom
    image: dtcooper/crazyarms-zoom:${CRAZYARMS_VERSION:-latest}
    restart: always
    build:
      context: ./zoom
    volumes:
      - services_config:/config
      - zoom_user_home:/home/user
    cap_add:
      - SYS_ADMIN
    environment:
      TZ: ${TIMEZONE:-US/Pacific}

volumes:
  zoom_user_home:
